# docker-compose.yml
services:
  backend:
    build: ./backend/root
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/root:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/root/djangoProject1/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: 
    container_name: db
    environment:
      - 
      - 
      - 
    volumes:
      - 

volumes:
  postgres_data: