# Generated by Django 5.0.4 on 2024-05-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='epantherid',
        ),
    ]