# Generated by Django 5.0.4 on 2025-02-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_epantherid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor/Administrator'), ('User', 'User')], default='User', help_text='User role in the system', max_length=50, verbose_name='role'),
        ),
    ]