# Generated by Django 5.0.4 on 2025-02-18 20:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('variety', models.CharField(blank=True, max_length=50, null=True)),
                ('maturity_time', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('germination_time', models.IntegerField(blank=True, null=True)),
                ('spacing_x', models.IntegerField(blank=True, null=True)),
                ('spacing_y', models.IntegerField(blank=True, null=True)),
                ('sun_level', models.CharField(blank=True, choices=[('full sun', 'Fullsun'), ('partial sun', 'Partsun'), ('partial shade', 'Partshade'), ('full shade', 'Fullshade')], max_length=13, null=True)),
                ('planting_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_req', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('plant_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='epantherid',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Ad'), ('user', 'Us'), ('moderator', 'Mo')], default='user', max_length=9, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gardens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_x', models.IntegerField()),
                ('size_y', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Garden_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_date', models.DateField()),
                ('x_coordinate', models.IntegerField()),
                ('y_coordinate', models.IntegerField()),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.gardens')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_value', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('maturity_time__gte', 0)), name='check_maturity_pos'),
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('germination_time__gte', models.Q(('germination_time__isnull', True)))), name='check_germ_pos'),
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('spacing_x__gte', models.Q(('spacing_x__isnull', True)))), name='check_spacing_x_pos'),
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('spacing_y__gte', models.Q(('spacing_y__isnull', True)))), name='check_spacing_y_pos'),
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('planting_depth__gte', models.Q(('planting_depth__isnull', True)))), name='check_depth_pos'),
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('water_req__gte', models.Q(('water_req__isnull', True)))), name='check_water_pos'),
        ),
        migrations.AddField(
            model_name='garden_log',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.plants'),
        ),
        migrations.AddField(
            model_name='replies',
            name='forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.forums'),
        ),
        migrations.AddField(
            model_name='replies',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.replies'),
        ),
        migrations.AddField(
            model_name='replies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='reply_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.replies'),
        ),
        migrations.AddConstraint(
            model_name='gardens',
            constraint=models.CheckConstraint(check=models.Q(('size_x__gt', 0)), name='check_size_x_pos'),
        ),
        migrations.AddConstraint(
            model_name='gardens',
            constraint=models.CheckConstraint(check=models.Q(('size_y__gt', 0)), name='check_size_y_pos'),
        ),
        migrations.AddConstraint(
            model_name='garden_log',
            constraint=models.UniqueConstraint(fields=('garden_id', 'x_coordinate', 'y_coordinate'), name='unq_plot_space'),
        ),
        migrations.AddConstraint(
            model_name='garden_log',
            constraint=models.CheckConstraint(check=models.Q(('x_coordinate__gte', 0)), name='check_x_coor_pos'),
        ),
        migrations.AddConstraint(
            model_name='garden_log',
            constraint=models.CheckConstraint(check=models.Q(('y_coordinate__gte', 0)), name='check_y_coor_pos'),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('user_id', 'reply_id'), name='unq_vote'),
        ),
    ]