# Generated by Django 5.0.4 on 2025-03-07 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_forums_options_alter_garden_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=50, unique=True, verbose_name='username'),
        ),
    ]
